                                               CLAUSE

video 18,22

1 --- GROUP BY CLAUSE

USE DEMO
CREATE TABLE EMP(EMPN INT,ENAME VARCHAR(20),JOB VARCHAR(20),HIREYEAR INT,SALARY MONEY,DEPTNO INT)
SELECT*FROM EMP
ALTER TABLE EMP ADD LOCATION VARCHAR(20)
UPDATE EMP SET LOCATION='GHAZIPUR' WHERE LOCATION IS NULL

HOW MANY PEOPLE WORK ON A PARTICULAR DEPARTMENT OR NUBBER OF PEOPLE WORK ON EACH DEPARTMENT OR EACH LOCATION 

SELECT JOB,COUNT(*) FROM EMP GROUP BY JOB    

SELECT JOB,SUM(SALARY) FROM EMP GROUP BY JOB

SELECT JOB, MAX(SALARY),MIN(SALARY),AVG(SALARY) FROM EMP GROUP BY JOB

SELECT JOB, COUNT(*),DEPTNO FROM EMP GROUP BY JOB,DEPTNO 

2----HAVING CLAUSE =====> THIS CLAUSE USED ON AFTER GROUPING THE DATA IT IS MAINLY USED TO FILTERING THE GROUPED DATA 

SELECT JOB,COUNT(*) FROM EMP GROUP BY JOB    

WHICH JOB CONTAIN NUMBER OF EMPLOYEE LESS THAN 4

SELECT JOB,COUNT(*) FROM EMP GROUP BY JOB HAVING COUNT(*)<4

SELECT JOB, SUM(SALARY) FROM EMP GROUP BY JOB 

SELECT JOB, SUM(SALARY) FROM EMP GROUP BY JOB  HAVING SUM(SALARY)<100000

3----ROLLUP CLAUSE ROLLUP IS FINDING SUB AND GRAND TOTAL BASED ON A SINGLE COLUMN

4-----CUBE CLAUSE IS FINDING SUB AND GRAND TOTAL BASED ON MULTIPLE COLUMN 

THESE UPPER CLAUSE IS USED ALONG WITHY GROUP BY

TESTING:  

SELECT JOB,COUNT(*) FROM EMP GROUP BY ROLLUP(JOB)

SELECT JOB,COUNT(*) FROM EMP GROUP BY CUBE(JOB)   -------------> BOTH GIVE SAME OUTPUT ON SINGLE COLUMN
 SELECT*FROM EMP

-----------------------------------------------------------------------------------------------------------------------

SELECT JOB,COUNT(*), DEPTNO FROM EMP GROUP BY ROLLUP(JOB,DEPTNO) ---> IT GIVE OUTPUT BASED ON ON ONLY ONE COLLUMN AT A TIME



SELECT JOB,COUNT(*), DEPTNO FROM EMP GROUP BY CUBE(JOB,DEPTNO) ---->HERE WE GE GET GRAND TOTAL OF EMPLOYEE BASED ON DEPARTNO AS WELL AS JOB

SELECT*FROM EMP



 