                                   ------USE OF FOREGIN KEY AND PRIMARY KEY--

STEP1 

CREATE TABLE DEPARTMENT(DEPTNO INT PRIMARY KEY,DNAME VARCHAR(20),LOCATION VARCHAR(20))

STEP 2:

INSERT INTO DEPARTMENT VALUES(10,'SATYAM SOFTWARE','GHAZIPUR'),(20,'SATYAM SOFTWARE1','DELHI'),(30,'SATYAM SOFTWARE2','MUMBAI')
SELECT*FROM DEPARTMENT

STEP3:

CREATE TABLE EMPLOYEE(EMPID INT IDENTITY(100,1),EMPNAME VARCHAR(20),SALARY MONEY,DEPTNO INT FOREIGN KEY REFERENCES DEPARTMENT(DEPTNO))

TEST 

SELECT*FROM DEPARTMENT
SELECT*FROM EMPLOYEE

INSERT INTO EMPLOYEE VALUES('SATYAM',10000,10),('DEEPAK',20000,20),('SHUBHAM',30000,30)


          ------MAKING RELATION SHIP IN BETWEEN TABLES BY USING PRIMARY KEY AND FOREIGN KEY CONSTRAINTS WITH OUT CASCADE RULE----

THERE ARE THREE RULES COMES IN PICTURE 

1--> INSERCTION RULE IT IS FIXED RULE 
2--> UPDATION RULE
3--> DELETION RULE


STEP1 

CREATE TABLE PI(EID INT PRIMARY KEY,ENAME VARCHAR(20),SALARY MONEY)

STEP 2:

INSERT INTO PI VALUES(10,'SATYAM',10000),(20,'SHIVAM',20000),(30,'SUNDRAM',30000)
SELECT*FROM PI

STEP3:

CREATE TABLE P2(MBNO INT ,EADDRESS VARCHAR(20),EID INT FOREIGN KEY REFERENCES PI(EID))
ALTER TABLE P2 ALTER COLUMN MBNO BIGINT

STEP 4
INSERT INTO P2 VALUES(8004746210,'GHAZIPUR',10),(9773661840,'KOTA',20),(8858195850,'GHAZIPUR',30)


TESTING: 

INSERCTION RULE  IT IS USED WHEN PARENT TABLE NOT HAVE  MATCH DATA WITH CHILD TABLE INSERSCTION DATA 
---------------------------------------------------------------------------------------------------------
INSERT INTO P2 VALUES(8004746210,'GHAZIPUR',40) -- NOT ALLOWED

UPDATION RULE: 

UPDATE PI SET EID=1 WHERE EID=10  --NOT ALLOWED

DELETATION RULE:

DELETE FROM PI WHERE EID=10  --NOT ALLOWED

-- WE CANT CHANCE PARENT REFERENCE DATA WITHOUT CASCADE RULE 
--ALSO WE NOT INSERT DATA IN CHILD TABLE IF REFERENCE DATA NOT MATCH WITH PARENT REFENCE DATA

SELECT*FROM PI
SELECT*FROM P2

            ------MAKING RELATION SHIP IN BETWEEN TABLES BY USING PRIMARY KEY AND FOREIGN KEY CONSTRAINTS WITH CASCADE RULE----

NOTE--> WHEN WE WANT TO UPDATE AND DELETE OPERATION ON PARENT TABLE REFERENCE COLUMN ALONG WITH CHILD TABLE REFERENCE COLUMN 

ON UPDATE CASECADE==> THIS RULE WILL USE WHENEVER WE WANT TO UPDATE THE DATA FROM PARENT TABLE ALONG WITH CHILD TABLE 

ON DELETE CASECADE==> THIS RULE WILL USE WHEN EVER WE WANT TO DELETE THE DATA FROM PARENT TABLE ALONG WITH CHILD TABLE

NOTE--> CASCADE RULE ARE IMPOSING ON CHILD TABLE THAT FOREIGN KEY COLUMN ONLY


STEP1 

CREATE TABLE P1(EID INT PRIMARY KEY,ENAME VARCHAR(20),SALARY MONEY)

STEP 2:

INSERT INTO P1 VALUES(10,'SATYAM',10000),(20,'SHIVAM',20000),(30,'SUNDRAM',30000)
SELECT*FROM P1

STEP3:

CREATE TABLE C1(MBNO INT ,EADDRESS VARCHAR(20),EID INT FOREIGN KEY REFERENCES PI(EID) ON UPDATE CASCADE ON DELETE CASCADE)
ALTER TABLE C1 ALTER COLUMN MBNO BIGINT

STEP 4
INSERT INTO C1 VALUES(8004746210,'GHAZIPUR',10),(9773661840,'KOTA',20),(8858195850,'GHAZIPUR',30)

TESTING:

INSERCTION RULE
---------------
INSERT INTO C1 VALUES(8004746210,'GHAZIPUR',40) -- NOT ALLOWED

UPDATION RULE: 

UPDATE P1 SET EID=1 WHERE EID=10  

DELETATION RULE:

DELETE FROM P1 WHERE EID=10  

SELECT*FROM P1
SELECT*FROM C1


                               -- WORKING WITH  UNIQUE NULL AND CHECK--

UNIQUE==> RESTRICTED DUPLICATE DATA  BUT ACCEPTED NULL INTO COLUMN

SYNTAX: < COLUMN NAME > <DATA TYPE>[SIZE] UNIQUE

CREATE TABLE TEST3(SNO INT UNIQUE,LOCATION VARCHAR(40) UNIQUE)

TESTING:

INSERT INTO TEST3 VALUES(101,'GZP')

INSERT INTO TEST3 VALUES(101,'HYD')

INSERT INTO TEST3 VALUES(102,'GZB')

INSERT INTO TEST3 VALUES(NULL,NULL)

SELECT*FROM TEST3

NOT NULL-- RESTRICTED NULL BUT ACCEPTED DUPLICATE VALUE INTO A COLUMN 

SYNTAX:

<COLUMN NAME> <DATA TYPE>[SIZE] NOT NULL


CREATE TABLE TEST4(SNO INT NOT NULL,LOCATION VARCHAR(40) NOT NULL)

TESTING:


INSERT INTO TEST4 VALUES(101,'GZP')

INSERT INTO TEST4 VALUES(101,'HYD')

INSERT INTO TEST4 VALUES(102,'GZB')

INSERT INTO TEST4 VALUES(NULL,NULL)

SELECT*FROM TEST4

PRIMARY KEY: UNION+NOT NULL

CHECK: TO CHECK VALUE BEFORE  INSERTING INTO A COLUMN 
       APPLY A CONDITION ON COLUMN

SYNTAX:
<COLUMN NAME><DATA TYPE>[SIZE] CHECK(CONDITION)

EXAMPLE:

CREATE TABLE TEST5(EID INT,SALARY MONEY CHECK(SALARY>=5000))

TESTING:

INSERT INTO TEST5 VALUES(101,5000)
INSERT INTO TEST5 VALUES(102,4000)
INSERT INTO TEST5 VALUES(103,25000)



SELECT*FROM TEST5


 
