                              --------------------------------------------------
							               CURSOR IN TSQL LANGUAGE
                             ----------------------------------------------------

CURSOR:-> CURSOR IS A TEMPORARY MEMORY/TEMPORARY WORK STATION 
       -> WILL ALLOCATED BY DATA BASE SERVER AT A TIME OF DML OPERATION  ARE PERFORMING BY USER ON DATA BASE TABLES
	   -> FOR STORING DATA BASE TABLE

	                   ---------------------------------------------------------
					                     TYPES OF CURSOR
                       ---------------------------------------------------------

1: IMPLICIT CURSOR: -> DEFAULT CURSOR OF SQL SERVER DATA BASE
                    -> THIS CURSOR MEMORY IS ALLOCATED BY DATA BASE SERVER WHEN WE PERFORM DML OPERATION

2: EXPLICIT CURSOR: -> THIS TYPE OF CURSOR CREATED BY USER
                    -> FETCH DATA FROM TABLE IN ROW BY ROW MANNER
					
					     ----------------------------------------
					           WORK WITH EXPLICIT CURSOR
						 ----------------------------------------

1:-> DECLARE CURSOR OBJECT
     SYNTAX:
	        DECLARE <CURSOR NAME> CURSOR FOR SELECT*FROM <TABLE NAME>

2:-> OPEN CURSOR CONNECTION
     SYNTAX:
	        OPEN<CURSOR NAME>

3:-> FETCH DATA FROM CURSOR
     SYNTAX:
	        FETCH NEXT/FIRST/LAST/PRIOR/ABSOLUTE N/RELATIVE N FROM<CURSOR NAME> [INTO VARIABLE]

4:-> CLOSE CURSOR CONNECTION
     SYNTAX:
	       CLOSE<CURSOR NAME>

5:-> DEALLOCATE CURSOR MEMORY
	 SYNTAX:
	      DEALLOCATE<CURSOR NAME>          
		  
		                  ------------------------------------------
						     EMPLIMENTATION OF EXPLICIT CURSOR
						  ------------------------------------------	       

SELECT*FROM EMP1

THERE ARE SIX METHOD USE FOR EXPLICIT MANNER:

NEXT
FIRST
LAST
PRIOR
ABSOLUTE N
RELATIVE N

1: WITHOUT CURSOR VARIABLE

DECLARE C1 CURSOR SCROLL FOR SELECT*FROM EMP1
OPEN C1
FETCH LAST FROM C1
FETCH PRIOR FROM C1
FETCH ABSOLUTE 4 FROM C1
FETCH RELATIVE -2 FROM C1

FETCH FIRST FROM C1
FETCH NEXT FROM C1
CLOSE C1
DEALLOCATE C1

2: WITH CURSOR VARIABLE

DECLARE C1 CURSOR SCROLL FOR SELECT EID,NAME FROM EMP1

DECLARE @EID INT, @NAME VARCHAR(20) 
OPEN C1

FETCH LAST FROM C1 INTO @EID,@NAME
PRINT'THE EMPLOYEE'+'@NAME+'+'ID IS:-'+CAST(@EID AS VARCHAR)


FETCH PRIOR FROM C1 INTO @EID,@NAME
PRINT'THE EMPLOYEE'+'@NAME+'+'ID IS:-'+CAST(@EID AS VARCHAR)


FETCH ABSOLUTE 4 FROM C1 INTO @EID,@NAME
PRINT'THE EMPLOYEE'+'@NAME+'+'ID IS:-'+CAST(@EID AS VARCHAR)


FETCH RELATIVE -2 FROM C1 INTO @EID,@NAME
PRINT'THE EMPLOYEE'+'@NAME+'+'ID IS:-'+CAST(@EID AS VARCHAR)


FETCH FIRST FROM C1 INTO @EID,@NAME
PRINT'THE EMPLOYEE'+'@NAME+'+'ID IS:-'+CAST(@EID AS VARCHAR)


FETCH NEXT FROM C1 INTO @EID,@NAME
PRINT'THE EMPLOYEE'+'@NAME+'+'ID IS:-'+CAST(@EID AS VARCHAR)

CLOSE C1
DEALLOCATE C1
	                   
					   SP_HELP  EMP1








;