                                 ----WORKING WITH TABLED VALUE FUNCTION ---- VIDEO 28=29

IN THIS CASE A FUNCTION WILL RETURN MORE THAN ONE VALUE/ MORE THAN ONE COLUMN VALUE FROM THE TABLE 

SYNTAX: 

CREATE [OR ALTER] FUNCTION <FUNCTION NAME>(@<PARAMETER><DATA TYPE>[SIZE],..............................)

RETURNS TABLE
AS
RETURN(<SELECT QUERY/STATEMENT>)

SYNTAX: TO CALL A TABLE VALUED FUNCTION

SELECT*FROM<FUNCTION NAME>(VALUE/VALUES)

QUESTION--> CREATE TABLE VALUED FUNCTION TO ACCEPT DEPARTMENT NAME AS A PARAMETER AND RETURN THE LIST OF EMPLOYEE WHO ARE WORKING IN THE GIVEN DEPARTMENT NAME

USE DEMO

CREATE TABLE EMP2(EID INT, ENAME VARCHAR(40),SALARY MONEY,DEPTNAME VARCHAR(20))

SELECT*FROM EMP2

CREATE FUNCTION TVF1(@DEPTNAME VARCHAR(40))
RETURNS TABLE
AS
RETURN(SELECT*FROM EMP2 WHERE DEPTNAME=@DEPTNAME)

SELECT*FROM TVF1('.NET')