 
USE OF IDENTITY IN SQL TABLE:

CREATE TABLE EMP(EID INT IDENTITY,NAME VARCHAR(40),SALARY MONEY)

INSERT INTO EMP VALUES(1,'SATYAM',2300) NOT ALLOEWD BECAUSE WE NOT PASS IDENTITY VALUE

INSERT INTO EMP VALUES('SATYAM',2300) ALLOWED

INSERT INTO EMP(EID,NAME,SALARY) VALUES(2,'SHIVAM',2200)    NOT ALLOWED BECAUSE WE NOT PASS IDENTITY VALUES

INSERT INTO EMP(NAME,SALARY) VALUES('SHIVAM',2200)

INSERT INTO EMP VALUES('SUNDRAM',2400),('DHAN JI',2500),('VIRAT',2600),('SHUBH JI',2700)

SELECT*FROM EMP  CALL THE TABLE  FOR READING PURPOSE

CREATE TABLE EMP1(EID INT IDENTITY(100,5),NAME VARCHAR(20),SALARY MONEY) USER DEFINED SEED 

INSERT INTO EMP1 VALUES('SATYAM',4000),('DEEPAK',3000),('HARSHIT',2000),('SHUBHAM',1000)

SELECT*FROM EMP1

SET IDENTITY_INSERT EMP1 ON
INSERT INTO EMP1(EID,NAME,SALARY) VALUES(127,'DEEPAK',5000)
SET IDENTITY_INSERT EMP1 OFF

INSERT INTO EMP1(EID,NAME,SALARY) VALUES(126,'CHUTIYA',5000)  AFTER OFF IDENTITY_INSERT NOT POSSIBLE TO ADD OTHER ANY ROW

DELETE FROM EMP1 WHERE EID=125   TO DELETE SPECIFIC ROW AND COLUMN

SELECT*FROM EMP1 

TRUNCATE TABLE EMP1  TO DELEATE ALL ROW FROM TABLE

DROP TABLE EMP1  TO DELEATE A TABLE 


SET OPERATION ON TABLE 

SELECT*FROM EMP

CREATE TABLE EMP_GHAZIPUR(EID INT,NAME VARCHAR(20),SALARY MONEY)
SELECT*FROM EMP_GHAZIPUR

CREATE TABLE EMP_GHAZIABAD(EID INT,NAME VARCHAR(20),SALARY MONEY)
SELECT*FROM EMP_GHAZIABAD

SELECT*FROM EMP_GHAZIPUR
UNION
SELECT*FROM EMP_GHAZIABAD

SELECT*FROM EMP_GHAZIPUR
UNION ALL
SELECT*FROM EMP_GHAZIABAD

SELECT*FROM EMP_GHAZIPUR
INTERSECT
SELECT*FROM EMP_GHAZIABAD

SELECT*FROM EMP_GHAZIPUR EXCEPT SELECT*FROM EMP_GHAZIABAD
