                                ------WORKING WITH RANKING FUNCTION----26,27

-->TO ASSIGN THE RANK TO EACH ROW WISE & GROUP OF ROW WISE

 -->IF WE WANT TO GIVE SALARY TO OUR EMPLOYEE BASED ON PRIORITY THEN WE USE RANKING FUNCTION 

i ROW_NUMBER()

ii RANK()

iii DENSE_RANK()

SYNTAX:

       RANKING FUNCTION() OVER(PARTITION BY <COLUMN NAME> ORDER BY <COLUMN NAME> [ASC/DESC])

HERE

PARTITION BY--> OPTIONAL(ON GROUP OF ROW).

ORDER BY--> MANADATORY CLAUSE

EX:

USE DEMO

CREATE TABLE EMP1(EID INT,ENAME VARCHAR(20),SALARY MONEY,DEPTNO INT)

UPDATE EMP1 SET DEPTNO=50 WHERE DEPTNO IS NULL

ROW_NUMBER():

SELECT ENAME,SALARY,ROW_NUMBER() OVER(ORDER BY SALARY DESC) FROM EMP1

RANK():

SELECT ENAME,SALARY,RANK() OVER(ORDER BY SALARY DESC) AS RANKS FROM EMP1

DENSE RANK():

SELECT ENAME,SALARY,DENSE_RANK() OVER(ORDER BY SALARY DESC) FROM EMP1


ROW_NUMBER()

SELECT ENAME,SALARY,DEPTNO,ROW_NUMBER() OVER(PARTITION BY DEPTNO ORDER BY SALARY DESC) AS RANKS FROM EMP

RANK():

SELECT ENAME,SALARY,DEPTNO,RANK() OVER(PARTITION BY DEPTNO ORDER BY SALARY DESC) AS RANKS FROM EMP

DENSE():

SELECT ENAME,SALARY,DEPTNO,DENSE_RANK() OVER(PARTITION BY DEPTNO ORDER BY SALARY DESC) AS RANKS FROM EMP


SELECT*FROM EMP1
