
 --VIDEO 25,34

STORED FUNCTION IN T/SQL LANGUAGE 

A FUNCTION IS A BLOCK OF CODE WHICH WILL PERFORM SOME OPERATION ON THE GIVEN VALUE AND MUST RETURN A VALUE

STORED FUNCTION ARE ALSO CALLED USER DEFINED  FUNCTION IN T/SQL

THE USER WILL DEFINE TWO TYPE OF STORED FUNCTION 

1--> SCALER VALUED FUNCTION
2--> TABLE VALUED FUNCTION

                               ---- WORKING WITH SCALER VALUED FUNCTION---

THIS TYPE OF FUNCTION WILL RETURN A SINGLE VALUE OR A SINGLE COLUMN VALUE FROM THE TABLE 

SYNTAX..

CREATE [OR ALTER] FUNCTION <FNAME>(@<PARAMETERNAME1><DATA TYPE>[SIZE],..........................)

note: ALTER command are optional when we want any type of modification in function then we use ALTER command
 
 RETURNS<RETURN PARAMETER/ATTRIBUTE/VARIABLE DATA TYPE>
 AS
 BEGIN
 <FUNCTION BODY/STATEMENT>
 RETURN  <PARAMETER/ATTRIBUTE/VARIABLE NAME>
 END

 SYNTAX TO CALL SCALER VALUED FUNCTION :

 SELECT dbo.<FUNCTION NAME>(VALUE/VALUES)

 QUESTION---> CREATE A SCALER VALUED FUNCTION TO RETURN THE GROSS SALARY OF EMPLOYEE BASED ON THE FOLLOWING CONDITION

 i- HRA -10%
 ii- DA- 20%
 iii- PF-10%

 TO FIND GROSS SALARY OF THE EMPLOYEE?

 SOLUTION--> 

 USE SATYAM

 SELECT*FROM EMPLOYEE

 CREATE FUNCTION GRSAL(@EMPID INT)
 RETURNS MONEY
 AS
 BEGIN

 DECLARE @BASIC MONEY,@HRA MONEY,@DA MONEY,@PF MONEY, @GROSS MONEY

 SELECT @BASIC=SALARY FROM EMPLOYEE WHERE EMPID=@EMPID

 SET @HRA=@BASIC*0.1
 SET @DA=@BASIC*0.2
 SET @PF=@BASIC*0.1

 SET @GROSS=@BASIC+@HRA+@DA+@PF
 RETURN @GROSS
 END
  
 SELECT dbo.GRSAL(102)

 SELECT*FROM EMPLOYEE

                            ----WORKING WITH TABLED VALUE FUNCTION ---- VIDEO 28=29

IN THIS CASE A FUNCTION WILL RETURN MORE THAN ONE VALUE/ MORE THAN ONE COLUMN VALUE FROM THE TABLE 

SYNTAX: 

CREATE [OR ALTER] FUNCTION <FUNCTION NAME>(@<PARAMETER><DATA TYPE>[SIZE],..............................)

RETURNS TABLE
AS
RETURN(<SELECT QUERY/STATEMENT>)

SYNTAX: TO CALL A TABLE VALUED FUNCTION

SELECT*FROM<FUNCTION NAME>(VALUE/VALUES)

QUESTION--> CREATE TABLE VALUED FUNCTION TO ACCEPT DEPARTMENT NAME AS A PARAMETER AND RETURN THE LIST OF EMPLOYEE WHO ARE WORKING IN THE GIVEN DEPARTMENT NAME

USE DEMO

CREATE TABLE EMP2(EID INT, ENAME VARCHAR(40),SALARY MONEY,DEPTNAME VARCHAR(20))

SELECT*FROM EMP2

CREATE FUNCTION TVF1(@DEPTNAME VARCHAR(40))
RETURNS TABLE
AS
RETURN(SELECT*FROM EMP2 WHERE DEPTNAME=@DEPTNAME)

SELECT*FROM TVF1('.NET')
