
CREATE DATABASE DEMO;

USE SATYAM

CREATE TABLE EMPLOYEE( EMPID INT,EMPNAME VARCHAR(20),ESALARY MONEY,EAGE INT) 


ALTER TABLE EMPLOYEE ALTER COLUMN EMPNAME CHAR (50)

SP_HELP EMP
ALTER TABLE EMPDETAIL ADD EMPDETAIL VARCHAR (60)

ALTER TABLE EMPLOYEE ALTER COLUMN ; 

SP_RENAME 'EMPLOYEE.EDETAIL','EMPADDRESS'

SP_RENAME 'EMPDETAIL','EMP'
ALTER TABLE EMPDETAIL DROP COLUMN EMPADDRESS 

CREATE TABLE STUDENT(STUID INT,STUDNAME VARCHAR(20),STUFEE INT,STUAGE INT)
SP_HELP STUDENT
ALTER TABLE STUDENT ALTER COLUMN STUDNAME VARCHAR(50)
SP_HELP STUDENT
ALTER TABLE STUDENT ADD  STUADDRESS VARCHAR(50)
ALTER TABLE STUDENT ALTER COLUMN STUFEE DECIMAL(6,2)
ALTER TABLE STUDENT ALTER COLUMN  STUAGE  TINYINT
SP_HELP STUDENT
SP_RENAME 'STUDENT.STUADDRESS','SADDRESS'
SP_HELP STUDENT
SP_RENAME 'STUDENT','STUDENT'
SP_HELP STUDENT
TRUNCATE TABLE STUDENT
SP_HELP STUDENT
DROP TABLE STUDENT 
SP_HELP STUDENT
INSERT INTO STUDENT VALUES (103,'SHIVAM',350,20,'GHAZIPUR')
INSERT INTO STUDENT(STUID,STUDNAME ,STUFEE,STUAGE) VALUES(102,'SUNDRAM',6000,23)
SELECT*FROM STUDENT
UPDATE STUDENT SET SADDRESS='GHAZIABAD' WHERE SADDRESS='GHAZIPUR'
DELETE FROM STUDENT WHERE STUFEE=5000