	                                 ----------------------------------
				                    		STORED PROCEDURE
                                     ---------------------------------- VIDEO 37,41

DEFINITION: 
-----------
             ==> STORED PROCEDURE IS NOTHING BUT BLOCK OF CODE
			 ==> TO PERFORM SOME OPERATION ON THE GIVEN LOGIC
			 ==> PRE COMPILED BLOCK(i.e. FIRST COMPILATION OF CODE ONLY)
			 ==> APPLICATION PERFORMANCE WILL WE INCREASE
			 ==> STORED PROCEDURE BLOCK CODE CAN BE REUSE IN ANY APPLICATION(.NET,JAVA)

			                    --------------------------------------------
			                      TYPES OF PARAMETER OF A STORED PROCEDURE
                                --------------------------------------------

1-> IN/INPUT PARAMETER
2-> OUT/OUTPUT PARAMETER

SYNTAX:
       CREATE[OR ALTER] PROCEDURE <PROCEDURE NAME> (<@PARAMETER NAME><DATA TYPE>[SIZE]<TYPES OF PARAMETER>,................)
       AS
       BEGIN
       <PROCEDURE BODY/STATEMENT>
       END
 
SYNTAX TO CALL A STORED PROCEDURE 

        EXECUTE <PROCEDURE NAME>VALUE/VALUES

1--> IN/INPUT
 => DEFAULT PARAMETER OF STORED PROCEDURE 
 => WILL STORE THE INPUT VALUES SEND BY USER TO PROCEDURE 
                           ---STORED PROCEDURE BY USING DEFAULT PARAMETER---

QUESTION:==> CREATE A PROCEDURE TO INPUT EMPLOYEE DETAIL INTO A TABLE

SOLUTION: USE MYCLASS
          
          SELECT*FROM EMP

          CREATE PROCEDURE SPINPUT(@EID INT,@NAME VARCHAR(40),@SALARY MONEY,@DEPTN VARCHAR(20))
		  AS
		  BEGIN
		  INSERT INTO EMP(EID,NAME,SALARY,DEPTN) VALUES(@EID,@NAME,@SALARY,@DEPTN)
		  END

		  SET IDENTITY_INSERT EMP ON

		  EXECUTE SPINPUT 10,'AA',25000,'GZP'


		  BEGIN TRANSACTION
		  TRUNCATE TABLE EMP

		  BEGIN TRANSACTION
		  ROLLBACK

		  SELECT*FROM EMP

2--> OUT/OUTPUT
=> NEVER RETURN VALUE
=> WE WANT TO RETURN A VALUE FROM STORED PROCEDURE THEN WE USE 'OUT' PARAMETER

                      --STORED PROCEDURE  BY USING  "OUT" PARAMETER -- 

THERE ARE THREE STEP TO USE OUT PARAMETER

STEP-1: DECLARE THE BIND VARIABLE FOR OUT PARAMETER IN STORED PROCEDURE

SYNTAX:
DECLARE@<BIND VARIABLE NAME ><DATA TYPE>[SIZE]

STEP-2 ADDING THE BIND VARIABLE TO A STORED PROCEDURE

SYNTAX:
EXECUTE <PNAME> VALUE1,VALUE2,....@<BIND VARIABLE NAME> OUT;

STEP-3 TO PRINT BIND VARIABLE

PRINT @<BIND VAR.NAME>

QUESTION---> CREATE A STORED PROCEDURE FUNCTION TO INPUT EID AND RETURN THAT EMPLOYEE PROVIDENT FUND AND PROFECTION TAX ON SALARY BY FOLLOWING CONDITION
    PF--10%
	PT--20%

SOLUTION:
        
		USE MYCLASS
		  
        SELECT*FROM EMP

	   CREATE PROCEDURE SP1(@EID INT,@PF INT OUT,@PT INT OUT)
	   AS
	   BEGIN

	   DECLARE @SAL MONEY
	   SELECT @SAL=SALARY FROM EMP WHERE EID=@EID
	   SET @PF=@SAL*0.1
	   SET @PT=@SAL*0.2
	   END    

	   EXECUTE SP1 102 --NOT ALLOWED ERROR OCCUR BECAUSE IT NEED OUT PARAMETER VALUE BUT ITS VALUE RETURN BY PROCEDURE
	                   --TO REMOVE PROBLEM WE GO FOR FURTHER PROCEDURE

OUTPUT:

      DECLARE @bPF INT,@bPT INT
	  EXECUTE SP1 1,@bPF OUT,@bPT OUT

	  PRINT @bPF
	  PRINT @bPT
	  
	  PRINT 'PROVIDENT FUND IS: '+ CAST(@bPF AS VARCHAR)

	  
	  PRINT 'PROFESSIONAL TAX IS: '+ CAST(@bPT AS VARCHAR)

