                            -----SUB BLOCK IN T/SQL----

NAMED BLOCK: WRITTEN CODE IN SUB BLOCK IS SAVED IN DATABASE

THAT CODE CAN USE REUSE OF CODE(IE .NET/JAVA/DB)

TYPES OF BLOCKS
1. STORED PROCEDURE
2. STORED FUNCTION

WORKING WITH STORED PROCEDURE-----> THESE ARE PRECOMPLIED BLOCK(I.E. ONE TIME COMPILATION BLOCK)

WE CAN CREATE ASTORED PROCEDURE IN TWO WAYS 

1--> WITHOUT PARAMETER
2--> WITH PARAMETER

STORED PROCEDURE WITHOUT PARA METER --> PROCEDURE DOES NOT HAVE PARAMETER

SYNTAX: 

CREATE[OR ALTER] PROCEDURE <PNAME>
AS
BEGIN
<PROCEDURE BODY/STATEMENT>
END

SYNTAX TO CALL STORED PROCEDURE

EXECUTE<PNAME>;
OR
EXECUTE<PNAME>VALUE/(S)

EX:

SELECT*FROM EMP2 

CREATE PROCEDURE SP1
AS
BEGIN
SELECT*FROM EMP2
END

EXECUTE SP1