                                 -- SUB QUERY/ NESTED QUERY -- VIDEO 38,39,40,43

A QUERY INSIDE ANOTHER QUERY CALLED AS SUB/NESTED QUERY

SYNTAX:

SELECT*FROM<TABLE NAME>WHERE<CONDITION>(OUTER QUERY)(SELECT*FROM.....(SELECT*FROM...(SELECT*FROM...)))(==>INNER QUERY)

AS PER THE EXECITION PROCESS OF SUB QUERY IT AGAIN CLASSIFIED IN TWO WAYS

1--> NON CO RELATED SUB QUERY
 ==> IN NON CO RELATED SUB QUERY FIRST INNER QUERY IS EXECUTED AND LATER OUTEWR QUERY WILL EXECUTED
     I.E. OUTER QUERY ALWAYS DEPEND ON THE RESULT OF INNER QUERY


2--> CO RELATED SUB QUERY 
==> IN NON CORELATED SUB QUERY  FIRST OUTER QUERY IS ESECUTED AND LATER INNER QUERY WILL EXECUTED
     i.e. INNER  QUERY IS ALWAYS DEPEND UPON THYE RESULT OF OUTERT QUERY

	                       --WORKING WITH A NON CO-RELATED SUB QUERY--

DEFINITION : FIRST INNER QUERY IS EXECUTED AND LATER OUTER QUERY WILL ESECUTED

TYPES OF NON CORELATED SUB QUERY IS SIMPLY TWO TYPES--

---> SIMPLE/SINGLE ROW SUB QUERY
---> MULTIPLE ROW SUB QUERY

                            -- SIMPLE QUERY/ SINGLE ROW QUERY --

DEFNITION-- WHEN A SUB QUERY RETURNS A SINGLE VALUE IS CALLED AS SIMPLE SUB QUERY

EXAMPLE: WORK WITH A QUERY TO GET EMPLOYEE DETAILS FROM THE TABLE WHO ARE GETTING THE FIRST HIGHEST SALARY IN THE TABLE

SELECT*FROM EMP
SELECT*FROM EMP WHERE SALARY=2700

IF WE NOT KNOW HIGHEST SALARY THEN HOW TO GET MAXIMAM SALLARY GAINNER EMPLOYEE 
SELECT*FROM EMP WHERE SALARY= ?

EXPLATION:
                             ------------------------------------
                                SUB QUERY=OUTER+INNER QUERY
                              ------------------------------------

SELECT MAX(SALARY) FROM EMP 
---> RETURN VALUE--> 2700

STEP 2:

OUTER QUERY

SELECT*FROM EMP WHERE SALARY=MAX(SALARY)       ERROR OCCUR 

SELECT*FROM EMP WHERE SALARY= (INNER QUERY )

STEP 3:
               -------------------------
               SUB QUERY = OUTER+INNER
			   ---------------------------
 SELECT*FROM EMP WHERE SALARY=(SELECT MAX(SALARY) FROM EMP)


 QUESTION== WAQ TO DISPLAY EMPLOYEE DETAILS FROM THE TABLE WHOSE DEPARTMENT IS SAME AS THE DEPARTMENT OF THE EMPLOYEE A OR B

 SOLUTION== SELECT*FROM EMP

            ALTER TABLE EMP ADD DEPTN VARCHAR(20)
            
			SELECT DEPTN FROM EMP WHERE NAME='A' OR NAME='B'

            SELECT*FROM EMP WHERE DEPTN=(SELECT DEPTN FROM EMP WHERE NAME='SATYAM' OR NAME='DHAN JI')


			ERROR COME  TO OVER COME THIS PROBLEM WE USE  MULTIPLE ROW SUB QUERY
			 
			                
							--- WORKING WITH MULTIPLE ROW SUB QUERY---

DEFNITION: A SUB QUERY RETURN MORE THAN ONE VALUE IS CALLED AS MULTIPLE SUB QUERY WE CAN OPERATION IS "IN"

  SELECT*FROM EMP WHERE DEPTN IN (SELECT DEPTN FROM EMP WHERE NAME='SATYAM' OR NAME='SHIVAM')

 OR

 SELECT*FROM EMP WHERE DEPTN IN(SELECT DEPTN FROM EMP WHERE NAME IN('SATYAM','SHIVAM'))

                              -----------------------------------------------------------------
                                    DIFFERENCES BETWEEN CORELATED AND NON CO RELATED SUB QUERY
                              ------------------------------------------------------------------
HOW TO FIND NTH HIGHEST / LEAST SALARY EMPLOYEE DETAIL FROM THE TABLE?

                                      --NON CO-RELATED SUB QUERY--- 

1ST HIGEST SALARY EMPLOYEE DETAILS

SELECT MAX(SALARY) FROM EMP


SELECT*FROM EMP WHERE SALARY=(SELECT MAX(SALARY) FROM EMP)

2ND HIGHEST SALARY EMPLOYEE DETAIL


SELECT*FROM EMP WHERE SALARY=(SELECT MAX(SALARY) FROM EMP WHERE SALARY<(SELECT MAX(SALARY) FROM EMP))


                                   --CO RELATED SUB QUERY --

IN THIS CASE FIRST OUTER QUERY IS EXECUTED AND LATER INNER QUERY WILL EXECUTE

SYNTAX:
         SELECT*FROM<TABLE NAME> <TABLE ALIAS NAME> 
		 WHERE n-1=(SELECT COUNT(<CN>) FROM <TN> <TABLE ALIAS NAME2> )
		 WHERE <TABLE ALIAS NAME2>.<COLUMN NAME>(</>) <TABLE ALIAS NAME1>.<COLUMN NAME>

EXAMPLE: 

FIRST HIGEST SALARY DETAIL FROM TABLE(N=1)

SELECT*FROM EMP E1 WHERE 0=(SELECT COUNT(SALARY) FROM EMP E2 WHERE E2.SALARY>E1.SALARY)

SECOND HIGEST SALARY DETAIL FROM TABLE(N=2)

SELECT*FROM EMP E1 WHERE 1=(SELECT COUNT(SALARY) FROM EMP E2 WHERE E2.SALARY>E1.SALARY)

THIS PROCESS IS GONE AS SO ON UNTILL USER NOT GAIN DESIRE OUTPUT

